version: '3'
services:
  web:
    build:
        context: .
    expose:
      - "9292"
    volumes:
        - .:/home
  proxy:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
    links:
      - "web"
